name: Deploy to Vercel and Expo

on:
  push:
    branches:
      - main # Trigger on push to the 'main' branch

jobs:
  # Vercel Web Deployment
  vercel-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Use Node.js v18 for better pnpm compatibility
          
      - name: Install pnpm
        run: npm install -g pnpm
        
      - name: Install dependencies
        run: pnpm install
        
      - name: Build for Web
        run: pnpm run build # This runs `npx expo export:web`
        
      - name: Deploy to Vercel (Web)
        run: |
          pnpm install -g vercel
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --scope your-vercel-scope
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        
  # Expo Android Build
  expo-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Use Node.js v18 for better compatibility

      - name: Install pnpm
        run: npm install -g pnpm
        
      - name: Install dependencies
        run: pnpm install

      - name: Install expo-cli globally
        run: pnpm install -g expo-cli  # Install expo-cli globally

      - name: Build Android with Expo
        run: |
          expo login --username ${{ secrets.EXPO_USERNAME }} --password ${{ secrets.EXPO_PASSWORD }}
          expo build:android --no-publish # Build the APK without publishing it
          
      - name: Upload APK (optional)
        run: |
          echo "APK uploaded to Expo Build"
          # You can add steps here to upload APK to an S3 bucket or other deployment service if needed.
