name: Deploy to Vercel and Expo

on:
  push:
    branches:
      - main

jobs:
  # Web Deployment to Vercel
  vercel-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
        
      - name: Install dependencies
        run: npm install
        
      - name: Build for Web
        run: npm run build
        
      - name: Deploy to Vercel (Web)
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --scope your-vercel-scope
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

  # Android Build via Expo
  expo-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Authenticate with Expo
        run: npx expo login -u ${{ secrets.EXPO_USERNAME }} -p ${{ secrets.EXPO_PASSWORD }}

      - name: Build Android App
        run: npx expo build:android
